package com.guconstantino.watchdraw.data

import android.content.Context
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.guconstantino.watchdraw.R

/** The signed-in user, as shown on the Profile screen. */
data class UserProfile(
    val name: String,
    val email: String,
    val photoUrl: String? = null
)

/**
 * Thin wrapper around Google Sign-In (play-services-auth). The signed-in account
 * is persisted by Google Play services itself, so [lastProfile] survives app
 * restarts without any extra storage on our side.
 *
 * The web client id used for [GoogleSignInOptions.Builder.requestIdToken] is
 * generated by the google-services Gradle plugin from `google-services.json`
 * (the OAuth client of type 3) and exposed as `R.string.default_web_client_id`.
 */
object AuthManager {

    fun client(context: Context): GoogleSignInClient {
        val options = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(context.getString(R.string.default_web_client_id))
            .requestEmail()
            .requestProfile()
            .build()
        return GoogleSignIn.getClient(context, options)
    }

    /** The currently signed-in user, or null if nobody is signed in. */
    fun lastProfile(context: Context): UserProfile? {
        val account = GoogleSignIn.getLastSignedInAccount(context) ?: return null
        return UserProfile(
            name = account.displayName ?: account.givenName ?: "",
            email = account.email ?: "",
            photoUrl = account.photoUrl?.toString()
        )
    }

    /** Signs the user out and invokes [onDone] on the main thread when finished. */
    fun signOut(context: Context, onDone: () -> Unit) {
        client(context).signOut().addOnCompleteListener { onDone() }
    }
}
